Remove header installation and GPG verification tasks

diff --git a/recipes/newrelic/ebpf/centos_internal.yml b/recipes/newrelic/ebpf/centos_internal.yml
--- a/recipes/newrelic/ebpf/centos_internal.yml
+++ b/recipes/newrelic/ebpf/centos_internal.yml
@@ -24,11 +24,8 @@ keywords:
 processMatch: []
 
 preInstall:
-  requireAtDiscovery: |  
-      if [[ "$EUID" -ne 0 ]]; then
-          echo "\033[0;31mERROR:\033[0m root privleges are required. Please use sudo."
-          exit 1
-      fi
+  discoveryMode:
+    - targeted
 
 install:
   version: "3"
@@ -44,7 +41,6 @@ install:
         # - task: add_gpg_key
         # - task: add_nr_source
         # - task: update_apt_nr_source
-        # - task: install_linux_headers
         # - task: install_ebpf_agent
 
     assert_pre_req:
@@ -68,7 +64,6 @@ install:
         - |
           IS_OPENSSL_INSTALLED=$(which openssl | wc -l)
           if [ $IS_OPENSSL_INSTALLED -eq 0 ] ; then
-            echo "openssl is required to run the newrelic install. Please install openssl and re-run the installation." >&2
             echo ""
             echo -e "\e[31mERROR:\e[0m openssl is required to run the newrelic install. Please install openssl and re-run the installation." >&2
             echo ""
@@ -90,6 +85,21 @@ install:
             echo ""
             exit 15
           fi
+        - |
+          IS_CURL_INSTALLED=$(which curl | wc -l)
+          if [ $IS_CURL_INSTALLED -eq 0 ] ; then
+            echo ""
+            echo -e "\e[31mERROR:\e[0m curl is required to run the newrelic install. Please install curl and re-run the installation." >&2
+            echo ""
+            exit 15
+          fi
+        - |
+          if ! sudo mkdir -p /px; then
+            echo ""
+            echo -e "\e[31mERROR:\e[0m Failed to create /px directory. Aborting installation."
+            echo ""
+            exit 16
+          fi
 
     check_existing_install:
       cmds:
@@ -97,7 +107,7 @@ install:
           PACKAGE_NAME="newrelic-ebpf-agent"
           echo "Checking if $PACKAGE_NAME is installed..."
           if yum list --installed 2>/dev/null | grep -qw "$PACKAGE_NAME"; then
-              echo "$PACKAGE_NAME is already installed. Please uninstall and then run the installation again."
+              echo -e "\033[0;31mERROR:\033[0m $PACKAGE_NAME is already installed. Please uninstall and then run the installation again."
               echo -e "\nRun the following command to uninstall:\n\nsudo yum remove $PACKAGE_NAME -y\n"
               exit 1
           fi
@@ -270,7 +280,6 @@ install:
                   echo "Creating directory for certificates: $TLS_CERT_PATH"
                   sudo mkdir -p "$TLS_CERT_PATH" || log_error_and_exit "Failed to create directory $TLS_CERT_PATH."
               fi
-
           }
 
           generate_tls_cert() {
@@ -298,7 +307,7 @@ install:
               sudo openssl genrsa -out "$TLS_CERT_PATH/ca.key" 4096 || log_error_and_exit "Failed to generate CA private key."
 
               # Create a self-signed certificate for the CA
-              sudo openssl req -new -x509 -sha256 -days 365 -key "$TLS_CERT_PATH/ca.key" -out "$TLS_CERT_PATH/ca.crt" -subj "/O=eBPF/CN=localhost" || log_error_and_exit "Failed to generate CA certificate."
+              sudo openssl req -new -x509 -sha256 -days 730 -key "$TLS_CERT_PATH/ca.key" -out "$TLS_CERT_PATH/ca.crt" -subj "/O=eBPF/CN=localhost" || log_error_and_exit "Failed to generate CA certificate."
 
               # Generate a private key for the server
               sudo openssl genrsa -out "$TLS_CERT_PATH/tls.key" 4096 || log_error_and_exit "Failed to generate server private key."
@@ -307,7 +316,7 @@ install:
               sudo openssl req -new -sha256 -key "$TLS_CERT_PATH/tls.key" -out "$TLS_CERT_PATH/server.csr" -config "$TLS_CERT_PATH/ssl.conf" -subj "/O=eBPF/CN=localhost" || log_error_and_exit "Failed to generate server CSR."
 
               # Sign the server CSR with the CA certificate to create the server certificate
-              sudo openssl x509 -req -sha256 -days 365 -in "$TLS_CERT_PATH/server.csr" -CA "$TLS_CERT_PATH/ca.crt" -CAkey "$TLS_CERT_PATH/ca.key" -set_serial 01 \
+              sudo openssl x509 -req -sha256 -days 730 -in "$TLS_CERT_PATH/server.csr" -CA "$TLS_CERT_PATH/ca.crt" -CAkey "$TLS_CERT_PATH/ca.key" -set_serial 01 \
                   -out "$TLS_CERT_PATH/tls.crt" -extensions req_ext -extfile "$TLS_CERT_PATH/ssl.conf" || log_error_and_exit "Failed to generate server certificate."
 
               echo "TLS certificates generated successfully in $TLS_CERT_PATH."
@@ -356,11 +365,10 @@ install:
 
           if [[ -z "$NEW_RELIC_LICENSE_KEY" ]]; then
               log_error_and_exit "NEW_RELIC_LICENSE_KEY is not found in the config file $CONFIG_FILE. Aborting installation."
-              exit 1
           fi
+
           if [[ -z "$DEPLOYMENT_NAME" ]]; then
               log_error_and_exit "DEPLOYMENT_NAME is empty. Aborting installation."
-              exit 1
           fi
           echo "Required config is found."   
 
@@ -381,37 +389,7 @@ install:
           if [[ -n "$LOCAL_PACKAGE_PATH" ]]; then
               echo "Local package path provided: $LOCAL_PACKAGE_PATH"
               if [[ -f "$LOCAL_PACKAGE_PATH" ]]; then
-                  #######
-
-                  linux_headers_base_url="http://nr-downloads-ohai-staging.s3.amazonaws.com/nr-ebpf-agent/artifacts/linux-headers/latest/"
-                  linux_headers_dir="/px"
-
-                  arch=$(uname -m)
-                  if [[ "$arch" == "x86_64" || "$arch" == "amd64" ]]; then
-                      arch="x86_64"
-                  elif [[ "$arch" == "aarch64" || "$arch" == "arm64" ]]; then
-                      arch="arm64"
-                  else
-                      echo "Unsupported architecture: $arch"
-                      exit 1
-                  fi
-                  kernel_version=$(uname -r)
-                  major=$(echo "$kernel_version" | cut -d. -f1)
-                  minor=$(echo "$kernel_version" | cut -d. -f2 | cut -d- -f1)
-                  header_filename="linux-headers-${arch}-${major}.${minor}.0.tar.gz"
-                  linux_headers_url="${linux_headers_base_url}${header_filename}"
-                  if ! curl --head --silent --fail "$linux_headers_url" > /dev/null; then
-                      echo "File not found at $linux_headers_url"
-                      exit 1
-                  fi
-
-                  mkdir -p "$linux_headers_dir"
-
-                  curl -s "$linux_headers_url" -o "$linux_headers_dir/$header_filename"
-
-                  echo "Downloaded $header_filename to $linux_headers_dir"
-
-                  #######
+                  
                   echo "Installing the provided RPM package..."
                   yum install -y "$LOCAL_PACKAGE_PATH" || {
                       echo "Resolving missing dependencies..."
@@ -472,38 +450,6 @@ install:
     #       apt-get $OPTIONS update -qq -y
     #   # apt will return an error if fails to update any of its sources. Ignore these errors and let the "install_infra" task fail.
     #   ignore_error: true
-
-    # install_linux_headers:
-    #   cmds:
-    #     - |
-    #       linux_headers_base_url="http://nr-downloads-ohai-staging.s3.amazonaws.com/nr-ebpf-agent/artifacts/linux-headers/latest/"
-    #       linux_headers_dir="/px"
-
-    #       arch=$(uname -m)
-    #       if [[ "$arch" == "x86_64" || "$arch" == "amd64" ]]; then
-    #           arch="x86_64"
-    #       elif [[ "$arch" == "aarch64" || "$arch" == "arm64" ]]; then
-    #           arch="arm64"
-    #       else
-    #           echo "Unsupported architecture: $arch"
-    #           exit 1
-    #       fi
-    #       kernel_version=$(uname -r)
-    #       major=$(echo "$kernel_version" | cut -d. -f1)
-    #       minor=$(echo "$kernel_version" | cut -d. -f2 | cut -d- -f1)
-    #       header_filename="linux-headers-${arch}-${major}.${minor}.0.tar.gz"
-    #       linux_headers_url="${linux_headers_base_url}${header_filename}"
-    #       if ! curl --head --silent --fail "$linux_headers_url" > /dev/null; then
-    #           echo "File not found at $linux_headers_url"
-    #           exit 1
-    #       fi
-
-    #       mkdir -p "$linux_headers_dir"
-
-    #       curl -s "$linux_headers_url" -o "$linux_headers_dir/$header_filename"
-
-    #       echo "Downloaded $header_filename to $linux_headers_dir"
-    #   silent: true
 
     # install_ebpf_agent:
     #   cmds:
diff --git a/recipes/newrelic/ebpf/ubuntu_internal.yml b/recipes/newrelic/ebpf/ubuntu_internal.yml
--- a/recipes/newrelic/ebpf/ubuntu_internal.yml
+++ b/recipes/newrelic/ebpf/ubuntu_internal.yml
@@ -10,7 +10,7 @@ installTargets:
   - type: host
     os: linux
     platform: "ubuntu"
-    platformVersion: "(((20|21|22|24)\\.04))"
+    platformVersion: "(((20|22|24)\\.04))"
   - type: host
     os: linux
     platform: "debian"
@@ -49,7 +49,6 @@ install:
         - task: add_gpg_key
         - task: add_nr_source
         - task: update_apt_nr_source
-        - task: install_linux_headers
         - task: install_ebpf_agent
 
     assert_pre_req:
@@ -94,6 +93,21 @@ install:
             echo ""
             exit 15
           fi
+        - |
+          IS_CURL_INSTALLED=$(which curl | wc -l)
+          if [ $IS_CURL_INSTALLED -eq 0 ] ; then
+            echo ""
+            echo -e "\e[31mERROR:\e[0m curl is required to run the newrelic install. Please install curl and re-run the installation." >&2
+            echo ""
+            exit 15
+          fi
+        - |
+          if ! sudo mkdir -p /px; then
+            echo ""
+            echo -e "\e[31mERROR:\e[0m Failed to create /px directory. Aborting installation."
+            echo ""
+            exit 16
+          fi
 
     check_existing_install:
       cmds:
@@ -105,6 +119,7 @@ install:
               echo -e "\nRun the following command to uninstall:\n\nsudo apt-get remove $PACKAGE_NAME -y\n"
               exit 1
           fi
+
 
     check_config_file:
       cmds:
@@ -301,7 +316,7 @@ install:
               sudo openssl genrsa -out "$TLS_CERT_PATH/ca.key" 4096 || log_error_and_exit "Failed to generate CA private key."
 
               # Create a self-signed certificate for the CA
-              sudo openssl req -new -x509 -sha256 -days 365 -key "$TLS_CERT_PATH/ca.key" -out "$TLS_CERT_PATH/ca.crt" -subj "/O=eBPF/CN=localhost" || log_error_and_exit "Failed to generate CA certificate."
+              sudo openssl req -new -x509 -sha256 -days 730 -key "$TLS_CERT_PATH/ca.key" -out "$TLS_CERT_PATH/ca.crt" -subj "/O=eBPF/CN=localhost" || log_error_and_exit "Failed to generate CA certificate."
 
               # Generate a private key for the server
               sudo openssl genrsa -out "$TLS_CERT_PATH/tls.key" 4096 || log_error_and_exit "Failed to generate server private key."
@@ -310,7 +325,7 @@ install:
               sudo openssl req -new -sha256 -key "$TLS_CERT_PATH/tls.key" -out "$TLS_CERT_PATH/server.csr" -config "$TLS_CERT_PATH/ssl.conf" -subj "/O=eBPF/CN=localhost" || log_error_and_exit "Failed to generate server CSR."
 
               # Sign the server CSR with the CA certificate to create the server certificate
-              sudo openssl x509 -req -sha256 -days 365 -in "$TLS_CERT_PATH/server.csr" -CA "$TLS_CERT_PATH/ca.crt" -CAkey "$TLS_CERT_PATH/ca.key" -set_serial 01 \
+              sudo openssl x509 -req -sha256 -days 730 -in "$TLS_CERT_PATH/server.csr" -CA "$TLS_CERT_PATH/ca.crt" -CAkey "$TLS_CERT_PATH/ca.key" -set_serial 01 \
                   -out "$TLS_CERT_PATH/tls.crt" -extensions req_ext -extfile "$TLS_CERT_PATH/ssl.conf" || log_error_and_exit "Failed to generate server certificate."
 
               echo "TLS certificates generated successfully in $TLS_CERT_PATH."
@@ -383,66 +398,6 @@ install:
           if [[ -n "$LOCAL_PACKAGE_PATH" ]]; then
               echo "Local Debian package path provided: $LOCAL_PACKAGE_PATH"
               if [[ -f "$LOCAL_PACKAGE_PATH" ]]; then
-
-                  #######
-
-                  base_url="http://nr-downloads-ohai-staging.s3.amazonaws.com/nr-ebpf-agent/artifacts/linux-headers/latest/"
-                  linux_headers_dir="/px"
-                  GPG_KEYRING="/tmp/newrelic-ebpf.gpg"
-                  GPG_KEY_URL="https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg"
-
-                  arch=$(uname -m)
-                  if [[ "$arch" == "x86_64" || "$arch" == "amd64" ]]; then
-                      arch="x86_64"
-                  elif [[ "$arch" == "aarch64" || "$arch" == "arm64" ]]; then
-                      arch="arm64"
-                  else
-                      log_error_and_exit "Unsupported architecture: $arch"
-                  fi
-                  kernel_version=$(uname -r)
-                  major=$(echo "$kernel_version" | cut -d. -f1)
-                  minor=$(echo "$kernel_version" | cut -d. -f2 | cut -d- -f1)
-                  header_filename="linux-headers-${arch}-${major}.${minor}.0.tar.gz"
-                  signature_filename="linux-headers-${arch}-${major}.${minor}.0.tar.gz.sig"
-                  linux_headers_url="${base_url}${header_filename}"
-                  signature_url="${base_url}${signature_filename}"
-                  if ! curl --head --silent --fail "$linux_headers_url" > /dev/null; then
-                      log_error_and_exit "File not found at $linux_headers_url"
-                  fi
-
-                  if ! curl --head --silent --fail "$signature_url" > /dev/null; then
-                      log_error_and_exit "Signature file not found at $signature_url"
-                  fi
-
-                  mkdir -p "$linux_headers_dir"
-
-                  curl -s "$linux_headers_url" -o "$linux_headers_dir/$header_filename"
-                  echo "Downloaded $header_filename to $linux_headers_dir"
-
-                  curl -s "$signature_url" -o "$linux_headers_dir/$signature_filename"
-                  echo "Downloaded $signature_filename to $linux_headers_dir"
-
-                  #GPG verification
-
-                  # Download the GPG public key
-                  curl -fsSL "$GPG_KEY_URL" -o "$GPG_KEYRING" || log_error_and_exit "Failed to download GPG key."
-                  echo "Downloaded GPG public at $GPG_KEYRING"
-
-                  # Import the key into a temporary keyring
-                  gpg --no-default-keyring --keyring /tmp/newrelic-ebpf-keyring.gpg --import "$GPG_KEYRING" >/dev/null 2>&1 || log_error_and_exit "Failed to import GPG key."
-                  echo "Imported GPG key into $GPG_KEYRING"
-
-                  # Verify the package
-                  gpg --no-default-keyring --keyring /tmp/newrelic-ebpf-keyring.gpg --verify "$linux_headers_dir/$signature_filename" "$linux_headers_dir/$header_filename"
-                  if [[ $? -eq 0 ]]; then
-                    echo "GPG verification successful: "$linux_headers_dir/$header_filename" is signed and valid."
-                    rm -f "$GPG_KEYRING"
-                  else
-                    log_error_and_exit "GPG verification failed!"
-                  fi
-                  
-
-                  #######
                   
                   echo "Installing the provided Debian package..."
                   apt-get install -y "$LOCAL_PACKAGE_PATH" || {
@@ -506,63 +461,6 @@ install:
       # apt will return an error if fails to update any of its sources. Ignore these errors and let the "install_infra" task fail.
       ignore_error: true
 
-    install_linux_headers:
-      cmds:
-        - |
-          base_url="http://nr-downloads-ohai-staging.s3.amazonaws.com/nr-ebpf-agent/artifacts/linux-headers/latest/"
-          linux_headers_dir="/px"
-          GPG_KEYRING="/tmp/newrelic-ebpf.gpg"
-          GPG_KEY_URL="https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg"
-
-          arch=$(uname -m)
-          if [[ "$arch" == "x86_64" || "$arch" == "amd64" ]]; then
-              arch="x86_64"
-          elif [[ "$arch" == "aarch64" || "$arch" == "arm64" ]]; then
-              arch="arm64"
-          else
-              log_error_and_exit "Unsupported architecture: $arch"
-          fi
-          kernel_version=$(uname -r)
-          major=$(echo "$kernel_version" | cut -d. -f1)
-          minor=$(echo "$kernel_version" | cut -d. -f2 | cut -d- -f1)
-          header_filename="linux-headers-${arch}-${major}.${minor}.0.tar.gz"
-          signature_filename="linux-headers-${arch}-${major}.${minor}.0.tar.gz.sig"
-          linux_headers_url="${base_url}${header_filename}"
-          signature_url="${base_url}${signature_filename}"
-          if ! curl --head --silent --fail "$linux_headers_url" > /dev/null; then
-              log_error_and_exit "File not found at $linux_headers_url"
-          fi
-
-          if ! curl --head --silent --fail "$signature_url" > /dev/null; then
-              log_error_and_exit "Signature file not found at $signature_url"
-          fi
-
-          mkdir -p "$linux_headers_dir"
-
-          curl -s "$linux_headers_url" -o "$linux_headers_dir/$header_filename"
-          echo "Downloaded $header_filename to $linux_headers_dir"
-
-          curl -s "$signature_url" -o "$linux_headers_dir/$signature_filename"
-          echo "Downloaded $signature_filename to $linux_headers_dir"
-
-          # Download the GPG public key
-          curl -fsSL "$GPG_KEY_URL" -o "$GPG_KEYRING" || log_error_and_exit "Failed to download GPG key."
-          echo "Downloaded GPG public at $GPG_KEYRING"
-
-          # Import the key into a temporary keyring
-          gpg --no-default-keyring --keyring /tmp/newrelic-ebpf-keyring.gpg --import "$GPG_KEYRING" >/dev/null 2>&1 || log_error_and_exit "Failed to import GPG key."
-          echo "Imported GPG key into $GPG_KEYRING"
-
-          # Verify the package
-          gpg --no-default-keyring --keyring /tmp/newrelic-ebpf-keyring.gpg --verify "$linux_headers_dir/$signature_filename" "$linux_headers_dir/$header_filename"
-          if [[ $? -eq 0 ]]; then
-            echo "GPG verification successful: "$linux_headers_dir/$header_filename" is signed and valid."
-            rm -f "$GPG_KEYRING"
-          else
-            log_error_and_exit "GPG verification failed!"
-          fi
-          
-      silent: true
     install_ebpf_agent:
       cmds:
         - |
@@ -578,7 +476,4 @@ install:
 postInstall:
   info: |2
       ⚙️  The eBPF Agent configuration file can be found in /etc/newrelic-ebpf-agent/newrelic-ebpf-agent.conf
-      Edit this file to make changes or configure advanced features for the agent. See the docs for options:
-      https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings
-      
-      Note: Process monitoring has been enabled by default - all other config options are left to the user.
+      Edit this file to make changes or configure advanced features for the agent.
