Use zypper for local package installation

diff --git a/recipes/newrelic/ebpf/suse_internal.yml b/recipes/newrelic/ebpf/suse_internal.yml
--- a/recipes/newrelic/ebpf/suse_internal.yml
+++ b/recipes/newrelic/ebpf/suse_internal.yml
@@ -392,14 +392,17 @@ install:
           if [[ -n "$LOCAL_PACKAGE_PATH" ]]; then
               echo "Local package path provided: $LOCAL_PACKAGE_PATH"
               if [[ -f "$LOCAL_PACKAGE_PATH" ]]; then
-                  
                   echo "Installing the provided RPM package..."
-                  yum install -y "$LOCAL_PACKAGE_PATH" || {
-                      echo "Resolving missing dependencies..."
-                      yum update -y || log_error_and_exit "Failed to perform yum upgrade."
-                      yum install -f -y || log_error_and_exit "Failed to resolve dependencies for the RPM package."
+                  # Attempt to install the local package directly.
+                  zypper --no-confirm install "$LOCAL_PACKAGE_PATH" || {
+                      echo "Failed to install the package. Resolving dependencies..."
+                      # Update the package list to get the latest dependency information.
+                      zypper --no-confirm update || log_error_and_exit "Failed to perform zypper update."
+
+                      # Attempt to install again, this time with a more aggressive dependency resolution.
+                      zypper --no-confirm --force-resolution install "$LOCAL_PACKAGE_PATH" || log_error_and_exit "Failed to resolve dependencies for the RPM package."
                   }
-                  echo "RPM package and its dependencies installed successfully."
+                  echo "Package and its dependencies installed successfully."
                   exit 123
               else
                   log_error_and_exit "The provided path does not point to a valid file: $LOCAL_PACKAGE_PATH"
