Add check for gpg suite

diff --git a/recipes/newrelic/ebpf/ubuntu_internal.yml b/recipes/newrelic/ebpf/ubuntu_internal.yml
--- a/recipes/newrelic/ebpf/ubuntu_internal.yml
+++ b/recipes/newrelic/ebpf/ubuntu_internal.yml
@@ -85,10 +85,12 @@ install:
             exit 15
           fi
         - |
+          IS_GPG_AGENT_INSTALLED=$(which gpg-agent | wc -l)
+          IS_GPG_CONNECT_AGENT_INSTALLED=$(which gpg-connect-agent | wc -l)
           IS_GPG_INSTALLED=$(which gpg | wc -l)
-          if [ $IS_GPG_INSTALLED -eq 0 ] ; then
+          if [ $IS_GPG_AGENT_INSTALLED -eq 0 ] || [ $IS_GPG_CONNECT_AGENT_INSTALLED -eq 0 ] || [ $IS_GPG_INSTALLED -eq 0 ]; then
             echo ""
-            echo -e "\e[31mERROR:\e[0m gpg is required to run the newrelic install. Please install gpg and re-run the installation." >&2
+            echo -e "\e[31mERROR:\e[0m GnuPG suite is required to run the newrelic install. Please install gnupg suite and re-run the installation." >&2
             echo ""
             exit 15
           fi
