Install linux headers with LOCAL_PACKAGE_PATH installation

diff --git a/recipes/newrelic/ebpf/ubuntu_internal.yml b/recipes/newrelic/ebpf/ubuntu_internal.yml
--- a/recipes/newrelic/ebpf/ubuntu_internal.yml
+++ b/recipes/newrelic/ebpf/ubuntu_internal.yml
@@ -408,6 +408,16 @@ install:
               echo "Local Debian package path provided: $LOCAL_PACKAGE_PATH"
               if [[ -f "$LOCAL_PACKAGE_PATH" ]]; then
                   
+                  KERNEL_VERSION=$(uname -r)
+                  echo "Installing linux headers for kernel version: $KERNEL_VERSION"
+                  if ! apt-get install -yq --no-install-recommends "linux-headers-$KERNEL_VERSION"; then
+                    echo ""
+                    echo -e "\e[31mERROR:\e[0m Failed to install linux headers for kernel $KERNEL_VERSION. Please ensure the correct headers are available and try again."
+                    echo ""
+                    exit 20
+                  fi
+                  echo "Linux headers installed successfully for kernel $KERNEL_VERSION."
+                  
                   echo "Installing the provided Debian package..."
                   apt-get install -y "$LOCAL_PACKAGE_PATH" || {
                       echo "Resolving missing dependencies for the Debian package..."
