Add fix for LOCAL_PACKAGE_PATH with CONFIG_FILE_PATH

diff --git a/recipes/newrelic/ebpf/ubuntu_yaml_config.yml b/recipes/newrelic/ebpf/ubuntu_yaml_config.yml
--- a/recipes/newrelic/ebpf/ubuntu_yaml_config.yml
+++ b/recipes/newrelic/ebpf/ubuntu_yaml_config.yml
@@ -235,6 +235,35 @@ install:
               exit 1
           }
 
+          install_from_local_package() {
+            if [[ -n "$LOCAL_PACKAGE_PATH" ]]; then
+                echo "Local Debian package path provided: $LOCAL_PACKAGE_PATH"
+                if [[ -f "$LOCAL_PACKAGE_PATH" ]]; then
+                    
+                    KERNEL_VERSION=$(uname -r)
+                    echo "Installing linux headers for kernel version: $KERNEL_VERSION"
+                    if ! apt-get install -yq --no-install-recommends "linux-headers-$KERNEL_VERSION"; then
+                      echo ""
+                      echo -e "\e[31mERROR:\e[0m Failed to install linux headers for kernel $KERNEL_VERSION. Please ensure the correct headers are available and try again."
+                      echo ""
+                      # exit 20
+                    fi
+                    echo "Linux headers installed successfully for kernel $KERNEL_VERSION."
+                    
+                    echo "Installing the provided Debian package..."
+                    apt-get install -y "$LOCAL_PACKAGE_PATH" || {
+                        echo "Resolving missing dependencies for the Debian package..."
+                        apt-get update -y || log_error_and_exit "Failed to perform apt-get upgrade."
+                        apt-get install -f -y || log_error_and_exit "Failed to resolve dependencies for the Debian package."
+                    }
+                    echo "Debian package and its dependencies installed successfully."
+                    exit 123
+                else
+                    log_error_and_exit "The provided path does not point to a valid file: $LOCAL_PACKAGE_PATH"
+                fi
+            fi
+          }
+
           # Handle custom config file path
           if [[ -n "${CONFIG_FILE_PATH:-}" ]]; then
             if [[ -f "$CONFIG_FILE_PATH" ]]; then
@@ -247,7 +276,7 @@ install:
                 echo "Symbolic link created successfully."
               fi
               echo "Configuration file ready at $CONFIG_FILE"
-              exit 0
+              install_from_local_package
             else
               log_error_and_exit "Custom configuration file $CONFIG_FILE_PATH does not exist."
             fi
@@ -444,32 +473,7 @@ install:
 
           echo "YAML configuration file created successfully at $CONFIG_FILE"
 
-          if [[ -n "$LOCAL_PACKAGE_PATH" ]]; then
-              echo "Local Debian package path provided: $LOCAL_PACKAGE_PATH"
-              if [[ -f "$LOCAL_PACKAGE_PATH" ]]; then
-                  
-                  KERNEL_VERSION=$(uname -r)
-                  echo "Installing linux headers for kernel version: $KERNEL_VERSION"
-                  if ! apt-get install -yq --no-install-recommends "linux-headers-$KERNEL_VERSION"; then
-                    echo ""
-                    echo -e "\e[31mERROR:\e[0m Failed to install linux headers for kernel $KERNEL_VERSION. Please ensure the correct headers are available and try again."
-                    echo ""
-                    # exit 20
-                  fi
-                  echo "Linux headers installed successfully for kernel $KERNEL_VERSION."
-                  
-                  echo "Installing the provided Debian package..."
-                  apt-get install -y "$LOCAL_PACKAGE_PATH" || {
-                      echo "Resolving missing dependencies for the Debian package..."
-                      apt-get update -y || log_error_and_exit "Failed to perform apt-get upgrade."
-                      apt-get install -f -y || log_error_and_exit "Failed to resolve dependencies for the Debian package."
-                  }
-                  echo "Debian package and its dependencies installed successfully."
-                  exit 123
-              else
-                  log_error_and_exit "The provided path does not point to a valid file: $LOCAL_PACKAGE_PATH"
-              fi
-          fi
+          install_from_local_package
 
     update_apt:
       cmds:
