Fix inappropriate logging

diff --git a/recipes/newrelic/ebpf/ubuntu_internal.yml b/recipes/newrelic/ebpf/ubuntu_internal.yml
--- a/recipes/newrelic/ebpf/ubuntu_internal.yml
+++ b/recipes/newrelic/ebpf/ubuntu_internal.yml
@@ -682,11 +682,17 @@ install:
                 # Force-Install the Software
                 echo "Attempting to install any missing dependencies or fixes broken packages."
                 apt-get $OPTIONS install -f
-                if [ $? -ne 0 ]; then 
+                if [ $? -ne 0 ]; then
                   exit 1
                 fi
-                echo "Installation is successful"
               fi
+            fi
+            # Verify package was actually installed
+            if ! dpkg -l | grep -q "^ii.*newrelic-ebpf-agent"; then
+              echo ""
+              echo -e "\e[31mERROR:\e[0m newrelic-ebpf-agent installation failed. Aborting installation."
+              echo ""
+              exit 1
             fi
           }
 
